### ISSUE TITLE
CSS中z-index的作用及结合position巧妙应用

### ISSUE THREAD

**Issue by pfzhengd** [pfzhengd/my-knowledge-notes#1]
### 适用（有效）
position:relative | absolute | fixed

### 不适用（无效）  
1. 设置了样式float。
2. position:static。

```
  z-index 属性指定了一个具有定位属性的元素及其子代元素的 z-order。 
  当元素之间重叠的时候，z-order 决定哪一个元素覆盖在其余元素的上方显
  示。 通常来说 z-index 较大的元素会覆盖较小的一个。

  对于一个已经定位的元素（即position属性值不是static的元素），
  z-index 属性指定：  
    1. 元素在当前堆叠上下文中的堆叠层级。
    2. 元素是否创建一个新的本地堆叠上下文。

  取值
  auto
  元素不会建立一个新的本地堆叠上下文。当前堆叠上下文中新生成的元素和父
  元素堆叠层级相同。
  <integer>
  整型数字是生成的元素在当前堆叠上下文中的堆叠层级。元素同时会创建一个
  堆叠层级为0的本地堆叠上下文。这意味着子元素的 z-indexes 不与元素外的
  其余元素的 z-index 进行对比。
  
  来自：https://developer.mozilla.org/zh-CN/docs/Web/CSS/z-index
```

在没有指定相对元素的z-index场景下，页面中z-index都是基于body同一堆叠上下文来比较优先级的，如果z-index存在相同值的场景，按布局元素的从上到下顺序算优先级。如下代码：

```html
<div class="dashed-box">Dashed box
  <span class="gold-box">Gold box</span>
  <span class="green-box">Green box</span>
</div>
```
```CSS
.dashed-box { 
  border: dashed;
  height: 8em;
  margin-bottom: 1em;
  margin-top: 2em;
}
.gold-box { 
  position: absolute;
  z-index: 3; /* put .gold-box above .green-box and .dashed-box */
  background: gold;
  width: 80%;
  left: 60px;
  top: 3em;
}
.green-box { 
  position: absolute;
  z-index: 2; /* put .green-box above .dashed-box */
  background: lightgreen;
  width: 20%;
  left: 65%;
  top: -25px;
  height: 7em;
  opacity: 0.9;
}
```
### 同页面多个堆叠上下文
  上面主要是基于z-index自身特性而讲，在实现项目中我们会遇上你的z-index与其它开发同学（模块）的z-index重叠或者z-index的值混乱，导致没有按指定的顺序展现。特别是如果在写公共组件的场景时，如果要求其它开发同学改，或者自个偷偷的改的话，个人感觉这种方式即不科学又low（哈哈）。

  有没有比较科学的方法去解决这个问题，肯定是有的。上面有提到z-index适用于position值为relative、absolute、fixed。结合相对定位与绝对定位的知识联想一下。在box元素中定义position值为relative,那么box元素中的子元素的z-index也是相对box元素来堆叠上下文的，多个box元就是多个相对的堆叠上下文。

  划分出来的堆叠上下文box元素自身，也会根据设置z-index的值堆叠顺序，其子元素的z-index值与另一个box元素下面的子元素z-index不产生冲突。
  
  如果box元素没有设置z-index，那么z-index的值为auto，元素不会建立一个新的本地堆叠上下文，并且堆叠上下文中新生成的元素和父元素堆叠层级相同，也就是说等同于没有划分多个堆叠上下文。

```html
<div class="dashed-box">Dashed box
  <span class="gold-box">Gold box</span>
  <span class="green-box">Green box</span>
</div>
<div class="dashed-box2">Dashed box2
  <span class="gold-box2">Gold box2</span>
  <span class="green-box2">Green box2</span>
</div>
````
```CSS
.dashed-box { 
  position: relative;
  border: dashed;
  z-index:3;
  height: 8em;
  margin-bottom: 1em;
  margin-top: 2em;
}
.gold-box { 
  position: absolute;
  z-index: 1; /* put .gold-box above .green-box and .dashed-box */
  background: gold;
  width: 80%;
  left: 60px;
  top: 3em;
}
.green-box { 
  position: absolute;
  z-index: 1; /* put .green-box above .dashed-box */
  background: red;
  width: 20%;
  left: 65%;
  top: -5px;
  height: 7em;
  opacity: 0.9;
}



.dashed-box2 { 
  position: relative;
  border: dashed;
  z-index:2;
  height: 8em;
  margin-bottom: 1em;
  margin-top: 2em;
}
.gold-box2 { 
  position: absolute;
  z-index: 3; /* put .gold-box above .green-box and .dashed-box */
  background: gold;
  width: 80%;
  left: 60px;
  top: 3em;
}
.green-box2 { 
  position: absolute;
  z-index: 11112; /* put .green-box above .dashed-box */
  background: yellow;
  width: 20%;
  left: 25%;
  top: -125px;
  height: 7em;
  opacity: 0.9;
}
```

### 效果预览
[codepen.io： https://codepen.io/pfzhengd/pen/ExxGRGj](https://codepen.io/pfzhengd/pen/ExxGRGj)
